##########################
# Simulation parameters
##########################

# Maximum refinement level of simulation, defined such that dx = box_size / 2^(amr_lrefine)
amr_lrefine_max: 11
# Minimum refinement level of simulation
amr_lrefine_min: 6

# Scale length of the box size in CGS
sim_unit_length : 1.8729852524984215e+20 

# boxsize in x, y, z in sim_unit_length
sim_size_x : 1 
sim_size_y : 1 
sim_size_z : 1 

# Origin of simulation
origin: 
  - 0.5 
  - 0.5 
  - 0.5 

# Arguments to pass to the simulation reader
sim_reader_args:
  # in this specific case the reader only needs an output number 
  output_number : 51


##########################
# Database parameters
##########################

# Cuttof limit for fluxes in log(n/cm^2), below which we consider them to be zero
# One for each radiation bin
log10_flux_low_limit:
  FUV   : -5.0
  HII   : -5.0
  HeII  : -6.0
  HeIII : -7.0

# Compression ratios for each of the fields in the models
compression_ratio:
  # number density
  dens :
    - 1   # Decimal precision
    - 2.0 # compression ratio
  
  # temperature
  temp :
    - 1
    - 5.0
  
  # cellsize
  dx:
    - 3
    - 1.0

  # Fluxes in their separate sub dictionary
  fluxes:
    FUV:
      - 1
      - 5.0
    HII:
      - 1
      - 5.0
    HeII:
      - 1
      - 5.0
    HeIII:
      - 1
      - 5.0    

##########################
# Raytracer  parameters
##########################

# Size of detector in units of boxsize
detector_size_x : 1
detector_size_y : 1

# Number of initial rays in each direction
Nxp : 512
Nyp : 512

# The resolving power of the cells by the rays.
# defined such that ray projecter area <= ray_max_area_frac * dx_cell^2
ray_max_area_frac : 0.25



